// <auto-generated />
using System;
using GCAMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GCAMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816143930_AddNotifsUniqueIndex2")]
    partial class AddNotifsUniqueIndex2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GCAMS.Models.AnecRecs.AnecRecs", b =>
                {
                    b.Property<int>("AnecRecsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnecRecsId"));

                    b.Property<int>("AnecRecNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfObserv")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObservedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ObserverRecs")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PeopleInvolved")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SceneMood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentBehavior")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StudentsID")
                        .HasColumnType("int");

                    b.HasKey("AnecRecsId");

                    b.HasIndex("StudentsID");

                    b.ToTable("AnecRecs");
                });

            modelBuilder.Entity("GCAMS.Models.Announcements.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<int?>("CounselorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("CounselorID");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("GCAMS.Models.Appointment.Appointments", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentID"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CounselorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StudentsID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentID");

                    b.HasIndex("CounselorID");

                    b.HasIndex("StudentsID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("GCAMS.Models.CaseNotes.CaseNotes", b =>
                {
                    b.Property<int>("CasenoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CasenoteId"));

                    b.Property<string>("BehaviorStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CounselProgess")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CounselorID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoalPlan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Homework")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Interventions")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionNo")
                        .HasColumnType("int");

                    b.Property<string>("SessionRelevance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SessionTopics")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecificGoal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrengthsChallenges")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StudentsID")
                        .HasColumnType("int");

                    b.HasKey("CasenoteId");

                    b.HasIndex("CounselorID");

                    b.HasIndex("StudentsID");

                    b.ToTable("CaseNotes");
                });

            modelBuilder.Entity("GCAMS.Models.Counselor.Counselor", b =>
                {
                    b.Property<int>("CounselorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CounselorID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("College")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CollegeCourse")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CounselorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("int");

                    b.Property<string>("PRCLicense")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PRCLicense2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostGraduateCourse")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PostGraduateStudies")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("WorkExperience")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WorkSchool")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CounselorID");

                    b.ToTable("Counselors");
                });

            modelBuilder.Entity("GCAMS.Models.Counselor.CounselorContactNumber", b =>
                {
                    b.Property<int>("CounselorContactNumberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CounselorContactNumberID"));

                    b.Property<int>("CounselorID")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CounselorContactNumberID");

                    b.HasIndex("CounselorID");

                    b.ToTable("CounselorContactNumbers");
                });

            modelBuilder.Entity("GCAMS.Models.Notifs.Notifs", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RecipientUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("RecipientUsername", "Type", "RelatedEntityType", "RelatedEntityId")
                        .IsUnique()
                        .HasFilter("[RelatedEntityType] IS NOT NULL AND [RelatedEntityId] IS NOT NULL");

                    b.ToTable("Notifs");
                });

            modelBuilder.Entity("GCAMS.Models.Students.EducationalBackground", b =>
                {
                    b.Property<int>("EducationalBackgroundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationalBackgroundID"));

                    b.Property<string>("ElementaryHonors")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ElementarySchool")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ElementaryYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondaryHonors")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SecondarySchool")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecondaryYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StudentsID")
                        .HasColumnType("int");

                    b.HasKey("EducationalBackgroundID");

                    b.HasIndex("StudentsID")
                        .IsUnique()
                        .HasFilter("[StudentsID] IS NOT NULL");

                    b.ToTable("EducationalBackgrounds");
                });

            modelBuilder.Entity("GCAMS.Models.Students.EmergencyContact", b =>
                {
                    b.Property<int>("EmergencyContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmergencyContactID"));

                    b.Property<string>("EmergencyContactAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("EmergencyContactAge")
                        .HasColumnType("int");

                    b.Property<string>("EmergencyContactOccupation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmergencyContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("StudentsID")
                        .HasColumnType("int");

                    b.HasKey("EmergencyContactID");

                    b.HasIndex("StudentsID")
                        .IsUnique()
                        .HasFilter("[StudentsID] IS NOT NULL");

                    b.ToTable("EmergencyContacts");
                });

            modelBuilder.Entity("GCAMS.Models.Students.EmergencyContactNumber", b =>
                {
                    b.Property<int>("EmergencyContactNumberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmergencyContactNumberID"));

                    b.Property<int>("EmergencyContactID")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmergencyContactNumberID");

                    b.HasIndex("EmergencyContactID");

                    b.ToTable("EmergencyContactNumbers");
                });

            modelBuilder.Entity("GCAMS.Models.Students.FamilyBackground", b =>
                {
                    b.Property<int>("FamilyBackgroundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FamilyBackgroundID"));

                    b.Property<int?>("FatherAge")
                        .HasColumnType("int");

                    b.Property<string>("FatherEducationalAttainment")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FatherName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FatherOccupation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MonthlyFamilyIncome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MotherAge")
                        .HasColumnType("int");

                    b.Property<string>("MotherEducationalAttainment")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MotherName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MotherOccupation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ParentsRelationshipStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StudentsID")
                        .HasColumnType("int");

                    b.HasKey("FamilyBackgroundID");

                    b.HasIndex("StudentsID")
                        .IsUnique()
                        .HasFilter("[StudentsID] IS NOT NULL");

                    b.ToTable("FamilyBackgrounds");
                });

            modelBuilder.Entity("GCAMS.Models.Students.FamilyContactNumber", b =>
                {
                    b.Property<int>("FamilyContactNumberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FamilyContactNumberID"));

                    b.Property<int>("FamilyBackgroundID")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FamilyContactNumberID");

                    b.HasIndex("FamilyBackgroundID");

                    b.ToTable("FamilyContactNumbers");
                });

            modelBuilder.Entity("GCAMS.Models.Students.HealthInformation", b =>
                {
                    b.Property<int>("HealthInformationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthInformationID"));

                    b.Property<string>("AbuseHistory")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Ailments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DrugHistory")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FamilyMentalHealthHistory")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Height")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Medication")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PsychiatricConsultation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("StudentsID")
                        .HasColumnType("int");

                    b.Property<string>("SuicideRiskHistory")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Weight")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("HealthInformationID");

                    b.HasIndex("StudentsID")
                        .IsUnique()
                        .HasFilter("[StudentsID] IS NOT NULL");

                    b.ToTable("HealthInformations");
                });

            modelBuilder.Entity("GCAMS.Models.Students.StudentContactNumber", b =>
                {
                    b.Property<int>("StudentContactNumberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentContactNumberID"));

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentsID")
                        .HasColumnType("int");

                    b.HasKey("StudentContactNumberID");

                    b.HasIndex("StudentsID");

                    b.ToTable("StudentContactNumbers");
                });

            modelBuilder.Entity("GCAMS.Models.Students.Students", b =>
                {
                    b.Property<int>("StudentsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentsID"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BirthOrder")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GradeLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Religion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StayingWith")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StuID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StuName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentsID");

                    b.HasIndex("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GCAMS.Models.Users.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PasswordChange")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GCAMS.Models.AnecRecs.AnecRecs", b =>
                {
                    b.HasOne("GCAMS.Models.Students.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GCAMS.Models.Announcements.Announcement", b =>
                {
                    b.HasOne("GCAMS.Models.Counselor.Counselor", "Counselor")
                        .WithMany()
                        .HasForeignKey("CounselorID");

                    b.Navigation("Counselor");
                });

            modelBuilder.Entity("GCAMS.Models.Appointment.Appointments", b =>
                {
                    b.HasOne("GCAMS.Models.Counselor.Counselor", "Counselor")
                        .WithMany()
                        .HasForeignKey("CounselorID");

                    b.HasOne("GCAMS.Models.Students.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentsID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Counselor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GCAMS.Models.CaseNotes.CaseNotes", b =>
                {
                    b.HasOne("GCAMS.Models.Counselor.Counselor", "Counselor")
                        .WithMany()
                        .HasForeignKey("CounselorID");

                    b.HasOne("GCAMS.Models.Students.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counselor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GCAMS.Models.Counselor.CounselorContactNumber", b =>
                {
                    b.HasOne("GCAMS.Models.Counselor.Counselor", "Counselor")
                        .WithMany("ContactNumbers")
                        .HasForeignKey("CounselorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counselor");
                });

            modelBuilder.Entity("GCAMS.Models.Students.EducationalBackground", b =>
                {
                    b.HasOne("GCAMS.Models.Students.Students", "Student")
                        .WithOne("EducationalBackground")
                        .HasForeignKey("GCAMS.Models.Students.EducationalBackground", "StudentsID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GCAMS.Models.Students.EmergencyContact", b =>
                {
                    b.HasOne("GCAMS.Models.Students.Students", "Student")
                        .WithOne("EmergencyContact")
                        .HasForeignKey("GCAMS.Models.Students.EmergencyContact", "StudentsID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GCAMS.Models.Students.EmergencyContactNumber", b =>
                {
                    b.HasOne("GCAMS.Models.Students.EmergencyContact", "EmergencyContact")
                        .WithMany("ContactNumbers")
                        .HasForeignKey("EmergencyContactID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmergencyContact");
                });

            modelBuilder.Entity("GCAMS.Models.Students.FamilyBackground", b =>
                {
                    b.HasOne("GCAMS.Models.Students.Students", "Student")
                        .WithOne("FamilyBackground")
                        .HasForeignKey("GCAMS.Models.Students.FamilyBackground", "StudentsID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GCAMS.Models.Students.FamilyContactNumber", b =>
                {
                    b.HasOne("GCAMS.Models.Students.FamilyBackground", "FamilyBackground")
                        .WithMany("ContactNumbers")
                        .HasForeignKey("FamilyBackgroundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyBackground");
                });

            modelBuilder.Entity("GCAMS.Models.Students.HealthInformation", b =>
                {
                    b.HasOne("GCAMS.Models.Students.Students", "Student")
                        .WithOne("HealthInformation")
                        .HasForeignKey("GCAMS.Models.Students.HealthInformation", "StudentsID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GCAMS.Models.Students.StudentContactNumber", b =>
                {
                    b.HasOne("GCAMS.Models.Students.Students", "Student")
                        .WithMany("ContactNumbers")
                        .HasForeignKey("StudentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GCAMS.Models.Students.Students", b =>
                {
                    b.HasOne("GCAMS.Models.Users.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GCAMS.Models.Counselor.Counselor", b =>
                {
                    b.Navigation("ContactNumbers");
                });

            modelBuilder.Entity("GCAMS.Models.Students.EmergencyContact", b =>
                {
                    b.Navigation("ContactNumbers");
                });

            modelBuilder.Entity("GCAMS.Models.Students.FamilyBackground", b =>
                {
                    b.Navigation("ContactNumbers");
                });

            modelBuilder.Entity("GCAMS.Models.Students.Students", b =>
                {
                    b.Navigation("ContactNumbers");

                    b.Navigation("EducationalBackground");

                    b.Navigation("EmergencyContact");

                    b.Navigation("FamilyBackground");

                    b.Navigation("HealthInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
